# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:2.7.15

pipelines:
  default:
    - step:
        name: build
        caches:
          - pip
          - cymodules
        script: # Modify the commands below to build your repository.
          - pip install --upgrade pip
          - pip install -r requirements.txt # install required packages
          - pip install future_fstrings # ensure fstrings are LAST
          - python setup.py build_ext --inplace # build Cython extensions
    - step:
        name: unittest
        script:
          - python2.7 cska/__init__.py --version
          - python2.7 -m unittest discover tests/ # run unit tests

definitions:
  caches:
    cymodules: cska/cy
